language: python

python:
  - "2.7"

env:
  - DJANGO="django==1.6.5"


install:
  -  python setup.py bdist_egg
  -  easy_install "dist/$(ls dist)"
  -  pip install -r requirements.txt
script:
  -  python setup.py test
